### ISSUE TITLE
Automatic sort on policies

### ISSUE THREAD

**Issue by lotusnoir** [jeremmfr/terraform-provider-junos#617] opened 2024-02-02 13:45 UTC
Hello,
 I ve noticed since a while that the content is sorted when its pushed into the srx, until now it was ok for me, but it become very annoying when you start to manage the policies. When you push a new rule, the one higher in the alphabet push all the others down, so it become totally unreadable very fast with a large set of rules and you can't really control what it's done:

For exemple i have in my firewall this 2 existing rules

```
test@fwv-08# show security policies global               
policy consul_any_to_any {
    match {
        source-address any;
        destination-address any;
        application [ TCP-UDP_8301-8302 TCP_8300 TCP_8500-8502 ];
        from-zone any;
        to-zone any;
    }
    then {
        permit;
    }
}
policy ping_any_to_any {
    match {
        source-address any;
        destination-address any;
        application junos-icmp-all;
        from-zone any;
        to-zone any;
    }
    then {
        permit;
    }
}
```
I want to push a new one called any_to_proxy that looks like

```
policy any_to_proxy {
    match {
        source-address any;
        destination-address [ proxy1 proxy3 proxy3 ];
        application TCP_80;
        from-zone any;
        to-zone [ Backend_Prod interco_pfs ] ;
    }
    then {
        permit;
    }
}
```

Here is the plan  when i push the rule:

 ```
# module.fwv-pia64-08.junos_security_global_policy.global[0] will be updated in-place
  ~ resource "junos_security_global_policy" "global" {
        id = "security_global_policy"

      ~ policy {
          ~ match_application         = [
              - "TCP-UDP_8301-8302",
              - "TCP_8300",
              - "TCP_8500-8502",
              + "TCP_80",
            ]
          ~ match_destination_address = [
              - "any",
              + "proxy1",
              + "proxy2",
              + "proxy3",
            ]
          ~ match_to_zone             = [
              - "any",
              + "Backend_Prod",
              + "interco_pfs",
            ]
          ~ name                      = "consul_any_to_any" -> "any_to_proxy"
            # (3 unchanged attributes hidden)
        }
      ~ policy {
          ~ match_application         = [
              - "junos-icmp-all",
              + "TCP-UDP_8301-8302",
              + "TCP_8300",
              + "TCP_8500-8502",
            ]
          ~ name                      = "ping_any_to_any" -> "consul_any_to_any"
            # (5 unchanged attributes hidden)
        }
      + policy {
          + match_application         = [
              + "junos-icmp-all",
            ]
          + match_destination_address = [
              + "any",
            ]
          + match_from_zone           = [
              + "any",
            ]
          + match_source_address      = [
              + "any",
            ]
          + match_to_zone             = [
              + "any",
            ]
          + name                      = "ping_any_to_any"
          + then                      = "permit"
        }
    }
```
 
So my question is how can i remove alphabetic sorting ? and eventually having an option to set the order of each rules, to be able to chose the rules order.

Thanks in advance

**Comment by lotusnoir** [comment] 2024-02-05 09:24
i've been thinking, maybe i should just put a prefix on the rules name.... ex 1_xxx

**Comment by jeremmfr** [comment] 2024-02-08 08:11
Hi :wave:

It looks like a duplicate of #160

`policy` blocks are ordered but not alphabetically. Blocks are ordered as they are ordered in the Terraform configuration file.  
When the provider updates the resource, policies on the Junos device are rewritten  to keep the defined order in the Terraform configuration file.

With ordered blocks, the Terraform plan output may look strange compared to the `show | compare` command on Junos when inserting or deleting a block that is not in the latest position, because Terraform is based only on block position to compute the difference between the old and new configuration.

An example with a resource based on your plan output :

```hcl
resource "junos_security_global_policy" "global" {
  #   policy {
  #     name                      = "any_to_proxy"
  #     match_source_address      = ["any"]
  #     match_destination_address = ["any"]
  #     match_application         = ["junos-https"]
  #     match_from_zone           = ["any"]
  #     match_to_zone             = ["any"]
  #   }
  policy {
    name                      = "consul_any_to_any"
    match_source_address      = ["any"]
    match_destination_address = ["any"]
    match_application         = ["junos-http"]
    match_from_zone           = ["any"]
    match_to_zone             = ["any"]
  }
  policy {
    name                      = "ping_any_to_any"
    match_source_address      = ["any"]
    match_destination_address = ["any"]
    match_application         = ["junos-icmp-all"]
    match_from_zone           = ["any"]
    match_to_zone             = ["any"]
  }
  #   policy {
  #     name                      = "any_to_proxy"
  #     match_source_address      = ["any"]
  #     match_destination_address = ["any"]
  #     match_application         = ["junos-https"]
  #     match_from_zone           = ["any"]
  #     match_to_zone             = ["any"]
  #   }
}
```

After creating the resource, if you uncomment the last `policy` block, the Terraform plan output looks like

```bash
Terraform will perform the following actions:

  # junos_security_global_policy.global will be updated in-place
  ~ resource "junos_security_global_policy" "global" {
        id = "security_global_policy"

      + policy {
          + match_application         = [
              + "junos-https",
            ]
          + match_destination_address = [
              + "any",
            ]
          + match_from_zone           = [
              + "any",
            ]
          + match_source_address      = [
              + "any",
            ]
          + match_to_zone             = [
              + "any",
            ]
          + name                      = "any_to_proxy"
          + then                      = "permit"
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

But if you uncomment the first `policy` block instead, the Terraform plan output looks like

```bash
Terraform will perform the following actions:

  # junos_security_global_policy.global will be updated in-place
  ~ resource "junos_security_global_policy" "global" {
        id = "security_global_policy"

      ~ policy {
          ~ match_application         = [
              - "junos-http",
              + "junos-https",
            ]
          ~ name                      = "consul_any_to_any" -> "any_to_proxy"
            # (5 unchanged attributes hidden)
        }
      ~ policy {
          ~ match_application         = [
              - "junos-icmp-all",
              + "junos-http",
            ]
          ~ name                      = "ping_any_to_any" -> "consul_any_to_any"
            # (5 unchanged attributes hidden)
        }
      + policy {
          + match_application         = [
              + "junos-icmp-all",
            ]
          + match_destination_address = [
              + "any",
            ]
          + match_from_zone           = [
              + "any",
            ]
          + match_source_address      = [
              + "any",
            ]
          + match_to_zone             = [
              + "any",
            ]
          + name                      = "ping_any_to_any"
          + then                      = "permit"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

Because Terraform found configuration change with 3 blocks (instead of 2), with parameters of the first block changed to new parameters, the second block with parameters of the old first block and a new third block with parameters of the old second block.

To confirm, this is the output of `show configuration | compare rollback 1` after:

- apply the resource update when uncommenting the latest `policy` block :

```bash
[edit security policies global]
      policy ping_any_to_any { ... }
+     policy any_to_proxy {
+         match {
+             source-address any;
+             destination-address any;
+             application junos-https;
+             from-zone any;
+             to-zone any;
+         }
+         then {
+             permit;
+         }
+     }
```

- apply the resource update when uncommenting the first `policy` block :

```bash
[edit security policies global]
+     policy any_to_proxy {
+         match {
+             source-address any;
+             destination-address any;
+             application junos-https;
+             from-zone any;
+             to-zone any;
+         }
+         then {
+             permit;
+         }
+     }
      policy consul_any_to_any { ... }
```

**Closed** 2024-02-08 08:12 UTC
Labels: duplicate, utilization question
