### ISSUE TITLE
Bug: "junos_system" resource with auto_snapshot propety as `false` returns error.

### ISSUE THREAD

**Issue by rslemon** [jeremmfr/terraform-provider-junos#591] opened 2023-12-07 08:07 UTC
Hello,

When we update the version of provider from 2.1.3 -> 2.3.2, "junos_system"  resource returns an error when auto_snapshot propety is `false` like below.
```
│ Error: Invalid boolean value
│ 
│   with junos_system.system,
│   on system.tf line 85, in resource "junos_system" "system":
│   85:   auto_snapshot                             = false
│ 
│ Must be true or null, false is not supported
```
According to the documentation, this is boolean, so false should still be supported?
```
auto_snapshot (Optional, Boolean)
Enable auto-snapshot when boots from alternate slice.
```
REF) https://registry.terraform.io/providers/jeremmfr/junos/latest/docs/resources/system

### Terraform and Provider Versions

```bash
2.3.2
```

### Terraform Configuration Files

```terraform
resource "junos_system" "system" {
  auto_snapshot  = false
}
```

### Expected Behavior

"junos_system" resource with auto_snapshot propety as `false` does not return error.

### Actual Behavior

"junos_system" resource returns an error when auto_snapshot propety set as `false`

### Steps to Reproduce

1. `terraform apply` with v2.1.3
2. `terraform apply` with v2.3.2

**Comment by jeremmfr** [comment] 2023-12-07 08:25
Duplicate of #532

Hi 👋 

You need to use `null` instead of `false`. Detail in #532

**Closed by jeremmfr** 2023-12-07 08:25 UTC
Labels: bug
